USE hr;

DELIMITER $$
CREATE PROCEDURE buscar_media_por_cargo (IN JOB VARCHAR(250))
BEGIN
SELECT ROUND(AVG(e.SALARY),2) AS `Média salarial`
FROM hr.employees e
RIGHT JOIN hr.jobs j
ON j.JOB_ID = e.JOB_ID
GROUP BY j.JOB_TITLE
HAVING j.JOB_TITLE = @JOB;
END$$
DELIMITER ;
