SELECT 
    CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) AS 'Nome completo',
    JOBS.JOB_TITLE AS 'Cargo',
    JOBH.START_DATE AS 'Data de início do cargo',
    DEPS.DEPARTMENT_NAME AS 'Departamento'
FROM
    HR.EMPLOYEES AS EMP
        JOIN
    HR.JOBS AS JOBS ON EMP.JOB_ID = JOBS.JOB_ID
        JOIN
    HR.DEPARTMENTS AS DEPS ON EMP.DEPARTMENT_ID = DEPS.DEPARTMENT_ID
        JOIN
    HR.JOB_HISTORY AS JOBH ON EMP.EMPLOYEE_ID = JOBH.EMPLOYEE_ID
ORDER BY CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) , JOBS.JOB_TITLE;
