USE hr;

DELIMITER $$
  CREATE FUNCTION buscar_quantidade_de_empregos_por_funcionario(EMAIL VARCHAR(200))
  RETURNS INT READS SQL DATA
BEGIN
  DECLARE TOTALJOBS INT;
  SELECT COUNT(*)
  FROM hr.employees AS E
  INNER JOIN hr.job_history AS JH
  ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
  WHERE E.EMAIL = EMAIL
  INTO TOTALJOBS;
  RETURN TOTALJOBS;
END $$
DELIMITER ;

SELECT BUSCAR_QUANTIDADE_DE_EMPREGOS_POR_FUNCIONARIO('NKOCHHAR');
