SELECT 
    CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) AS 'Nome completo',
    JOBS.JOB_TITLE AS 'Cargo',
    JOBH.START_DATE AS 'Data de início do cargo',
    DEPS.DEPARTMENT_NAME AS 'Departamento'
FROM
hr.employees AS EMP
JOIN
hr.jobs AS JOBS ON EMP.JOB_ID = JOBS.JOB_ID
JOIN
hr.job_history AS JOBH ON EMP.EMPLOYEE_ID = JOBH.EMPLOYEE_ID
JOIN
hr.departments AS DEPS ON EMP.DEPARTMENT_ID = DEPS.DEPARTMENT_ID
ORDER BY CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) DESC, JOBS.JOB_TITLE ASC;
