SELECT
CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS `Nome completo`,
CASE
WHEN MONTH(j.START_DATE) < 10 AND DAY(j.START_DATE) < 10
  THEN CONCAT('0', DAY(j.START_DATE), '/', '0', MONTH(j.START_DATE), '/', YEAR(j.START_DATE))
WHEN MONTH(j.START_DATE) < 10
  THEN CONCAT(DAY(j.START_DATE), '/', '0', MONTH(j.START_DATE), '/', YEAR(j.START_DATE))
WHEN DAY(j.START_DATE) < 10
  THEN CONCAT('0', DAY(j.START_DATE), '/', MONTH(j.START_DATE), '/', YEAR(j.START_DATE))
ELSE CONCAT(DAY(j.START_DATE), '/', MONTH(j.START_DATE), '/', YEAR(j.START_DATE))
END AS `Data de início`,

CASE
WHEN MONTH(j.END_DATE) < 10 AND DAY(j.END_DATE) < 10
  THEN CONCAT('0', DAY(j.END_DATE), '/', '0', MONTH(j.END_DATE), '/', YEAR(j.END_DATE))
WHEN MONTH(j.END_DATE) < 10
  THEN CONCAT(DAY(j.END_DATE), '/', '0', MONTH(j.END_DATE), '/', YEAR(j.END_DATE))
WHEN DAY(j.END_DATE) < 10
  THEN CONCAT('0', DAY(j.END_DATE), '/', MONTH(j.END_DATE), '/', YEAR(j.END_DATE))
ELSE CONCAT(DAY(j.END_DATE), '/', MONTH(j.END_DATE), '/', YEAR(j.END_DATE))
END AS `Data de rescisão`,

ROUND(DATEDIFF(j.END_DATE, j.START_DATE) / 365, 2) AS `Anos trabalhados`
FROM hr.job_history AS j
INNER JOIN hr.employees AS e
ON e.EMPLOYEE_ID = j.EMPLOYEE_ID
ORDER BY `Nome completo`, `Anos trabalhados`;
