SELECT COUNTRY.COUNTRY_NAME AS País , IF(REGIONS.REGION_NAME = 'EUROPE', 'incluído', 'não incluído') AS 'Status Inclusão'
FROM hr.countries AS COUNTRY
INNER JOIN hr.regions AS REGIONS
ON COUNTRY.REGION_ID = REGIONS.REGION_ID
ORDER BY País;

