SELECT 
    UPPER(CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME)) AS 'Nome completo',
    JOBH.START_DATE AS 'Data de início',
    EMP.SALARY AS 'Salário'
FROM
    HR.EMPLOYEES AS EMP
        JOIN
	HR.JOB_HISTORY AS JOBH ON EMP.EMPLOYEE_ID = JOBH.EMPLOYEE_ID
WHERE
    MONTH(JOBH.START_DATE) = 01
        OR MONTH(JOBH.START_DATE) = 02
        OR MONTH(JOBH.START_DATE) = 03
ORDER BY CONCAT(EMP.FIRST_NAME, ' ', EMP.LAST_NAME) , JOBH.START_DATE;
