-- Exiba os 05 primeiros países distintos dentre as pessoas consumidoras e as empresas fornecedoras, em ordem alfabética (w3schools).
-- Monte uma query que exiba 01 coluna com o alias "País" contendo o nome do país.
